/** MAX VIDEO RECORDING DURATION IN SECONDS */
export const MAX_VIDEO_RECORDING_DURATION = 61 * 1;

/** MAX VIDEO RECORDING DURATION IN MILLI SECONDS */
export const MAX_VIDEO_RECORDING_DURATION_MS =
  MAX_VIDEO_RECORDING_DURATION * 1000;

/** MAX LONG PRESS FOR LEAD REJECT 2s X 1000ms(1s) */
export const MAX_LONG_PRESS_FOR_LEAD_REJECT = 2 * 1000;
